name: CI/CD

on:
  push:
    branches: [ development ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.2' 

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: flutter analyze

      - name: Correr los tests
        run: flutter test 

  deploy:
    needs: test
    if: ${{ needs.test.result == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: production

      - name: Fetch all branches
        run: git fetch --all

      - name: Merge changes and deploy to production
        run: |
          git checkout production
          git merge origin/development
          git push origin production